name: eztaox
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  # - eztaox
  - arviz<=1.0.0
  - celerite
  - pip
  - pip:
    - eztaox@https://github.com/LSST-AGN-Variability/EzTaoX.git